image: node:6.9.4
clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Herokuサーバ未作成
          - npm init --yes
          - npm install
          - npm test
          # - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD