# BitBucketのPipelinesで使用する設定ファイルです。
# 詳細は https://confluence.atlassian.com/bitbucket/build-test-and-deploy-with-pipelines-792496469.html を参照。
image: node:6.9.4
clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD