# BitBucketのPipelinesで使用する設定ファイルです。
# 詳細は https://confluence.atlassian.com/bitbucket/build-test-and-deploy-with-pipelines-792496469.html を参照。
# 現在はmasterブランチでのみPipelineを実行するようにしています。
image: node:6.11.4
clone:
  depth: full

pipelines:
  branches:
    vueify:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm run build
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git vueify:master
